name: Build unsigned APK

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Build unsigned APK
              run: ./gradlew assembleDebug

            - name: Upload APK artifact
              uses: actions/upload-artifact@v4
              with:
                  name: app-debug-unsigned-apk
                  path: app/build/outputs/apk/debug/app-debug.apk
